[package]
name = "osdk-heap-allocator"
version = "0.15.2"
edition = "2024"
description = "The default slab-based heap allocator shipped with OSDK."
license = "MPL-2.0"
repository ="https://github.com/ldos-project/asterinas"
readme = "README.md"

[dependencies]
log = "0.4"
ostd = { version = "0.15.2", path = "../../../ostd" }
snafu = { workspace = true }

[lints]
workspace = true
